/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PostsNewPostImport } from './routes/posts/new-post'
import { Route as PostsPostidImport } from './routes/posts/$postid'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PostsNewPostRoute = PostsNewPostImport.update({
  id: '/posts/new-post',
  path: '/posts/new-post',
  getParentRoute: () => rootRoute,
} as any)

const PostsPostidRoute = PostsPostidImport.update({
  id: '/posts/$postid',
  path: '/posts/$postid',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/posts/$postid': {
      id: '/posts/$postid'
      path: '/posts/$postid'
      fullPath: '/posts/$postid'
      preLoaderRoute: typeof PostsPostidImport
      parentRoute: typeof rootRoute
    }
    '/posts/new-post': {
      id: '/posts/new-post'
      path: '/posts/new-post'
      fullPath: '/posts/new-post'
      preLoaderRoute: typeof PostsNewPostImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts/$postid': typeof PostsPostidRoute
  '/posts/new-post': typeof PostsNewPostRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts/$postid': typeof PostsPostidRoute
  '/posts/new-post': typeof PostsNewPostRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/posts/$postid': typeof PostsPostidRoute
  '/posts/new-post': typeof PostsNewPostRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/posts/$postid' | '/posts/new-post'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/posts/$postid' | '/posts/new-post'
  id: '__root__' | '/' | '/posts/$postid' | '/posts/new-post'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsPostidRoute: typeof PostsPostidRoute
  PostsNewPostRoute: typeof PostsNewPostRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsPostidRoute: PostsPostidRoute,
  PostsNewPostRoute: PostsNewPostRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/posts/$postid",
        "/posts/new-post"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/posts/$postid": {
      "filePath": "posts/$postid.tsx"
    },
    "/posts/new-post": {
      "filePath": "posts/new-post.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
